### ISSUE TITLE
test suite ays 8.1

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core8#543]
test
- scalability/performance
- features
- important: impact of change

### Component Testing:

- Validate parsing of blueprint. input and default args reach models.
- Validate dependency tree created from a blueprint is correct (producers, parents, ... etc)
- Validate `auto` creation on parent and consume schemas
- Validate created models are correct
- Validate deletion of models

### Scenario Testing:

- Prepare a test repo with expected results
- Validate directory structure and file contents after `ays blueprint`
- Validate `Run` filters (on actors (role/name), services and actions)
- Validate actions dependencies
- Validate run steps
- Validate Recurring actions:
 - validate handling that job execution time is < recurring action period (not handled in code yet)
 - validate that scheduler schedules jobs on time and parses input correctly
 - validate that actions are actually being executed
 - ERROR reporting (job should fail, step should be marked as failed and run as well. Subsequent steps should not run)
- Validate updating a value in a blueprint propagation. All relevant services must call `_processChange` and execute
- Validate `ays update` updates actions code. Again, check `_processChange` on all relevant services.

### Performance/Scalability Testing:

- Stress test recurring actions (schedule a lot of actions and check throughput and latency)
- Time huge blueprints (how long it takes to process the run)
- Cockpit testing:
 - Execute all REST API and validate output.
 - Stress test the server

Kanban: [link](https://waffle.io/gig-projects/org_development?search=ays81_testsuite:)

- [ ] ays81_testsuite: Validate parsing of blueprint [4h] #1278
- [ ] ays81_testsuite: Validate dependency tree [1d] #1279
- [ ] ays81_testsuite: Validate auto creation on parent and consume schemas [1d] #1280
- [ ] ays81_testsuite: Validate created models are correct [2h] #1281
- [ ] ays81_testsuite: Validate deletion of models [3h] #1282
- [ ] ays81_testsuite: Prepare 3 test repo [5h] #1283
- [ ] ays81_testsuite: Validate directory structure and file contents [5h] #1284
- [ ] ays81_testsuite: Validate Run filters [6h] #1285
- [ ] ays81_testsuite: Validate run steps [1d] #1286
- [ ] ays81_testsuite: validate actions dependencies [4h] #1287
- [ ] ays81_testsuite: Validate Recurring actions [1d] #1288
- [ ] ays81_testsuite: Validate updating a value in a blueprint propagation [3h] #1289
- [ ] ays81_testsuite: Validate ays update [4h] #1290
- [ ] ays81_testsuite: stress test recurring actions [2d] #1291
- [ ] ays81_testsuite: time huge blueprints [3h] #1292
- [ ] ays81_testsuite: cockpit testing [4d] #1293

# TODO
- need to move the specs to a code file in this repo ! and use markup there

**Comment by despiegk** [comment]
put as test() method on ays factory

**Comment by rkhamis** [comment]
Preliminary specs:

- Scalabilty/Performance testing of AYS cockpit. Through JMeter, test REST API (raml docs generated can be of help)
- Features:
  - `ays blueprint` inits all services
  -  `ays run` creates proper run as specified in blueprint
  - `ays update` works as expected when updating template,..
  -  local actortemplates override global templates
  - `ays destroy` destroys all relevant information
  - listing of: repos, blueprints, actors, services, runs, jobs
  - getting of: repos, blueprints, actors, services, runs, jobs
  - ...
- Impact of change: cleanup after testing.

**Comment by despiegk** [comment]
there seem to be more than 1 test attempt
- in root of jumpscale repo
- in test class of ays
- ays : https://github.com/Jumpscale/jumpscale_ays8_testenv

we need to identify what to do & focus upon
